# Generated by Django 2.1.3 on 2018-12-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microlly_blog', '0004_auto_20181205_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='a-slug'),
        ),
    ]
